syntax = "proto3";
package mfa.procurement.v1;

service ProcurementService {
  rpc GetPurchaseOrder (GetPurchaseOrderRequest) returns (PurchaseOrderReply);
  rpc GetPurchaseOrderExpectedItems (GetPOExpectedItemsRequest) returns (GetPOExpectedItemsReply);
}

message GetPurchaseOrderRequest {
  string id = 1;
}

message PurchaseOrderReply {
  string id = 1;
  string supplier_id = 2;
  string supplier_name = 3;
  string status = 4;
  string currency = 5;
  double total_cost = 6;
  string expected_date = 7;
}

message GetPOExpectedItemsRequest {
  string po_id = 1;
}

message PurchaseOrderExpectedItem {
  string product_code = 1;
  int32 ordered_qty = 2;
  int32 received_qty = 3;
  double unit_cost = 4;
}

message GetPOExpectedItemsReply {
  repeated PurchaseOrderExpectedItem items = 1;
}
